version: "3"

services:
    backend:
        build:
            context: .
            dockerfile: Backend/Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./Frontend:/app/Frontend # Монтируем локальную папку Backend внутрь контейнера
        depends_on:
            - mongo

    mongo:
        image: mongo:latest
        container_name: mongodb_auth
        ports:
            - "27017:27017"
        volumes:
            - ./mongo_data:/data/db
